### ISSUE TITLE
Output routine didn't use all of \box255.

### ISSUE THREAD

**Issue by ana-borges** [themiguelamador/ThesisIST#9]
The freshly downloaded template won't compile. The error
```
Output routine didn't use all of \box255.
```
appears several times.

Some googling seems to indicate that this can happen when LaTeX is updated. For reference, I'm using `TeX Live 2022/dev/Debian`.

**Comment by ana-borges** [comment]
I narrowed it down to importing `00.textpos.sty`. Not sure what it's used for. Things seem fine without importing it, but it's possible some formatting changed and I didn't notice.

**Comment by JoaoDomingos42** [comment]
Is this issue resolved? Did you end up getting any format changes without importing 00.textpos.sty?

**Comment by themiguelamador** [comment]
Error happens when putting a text break, so format change may happen there. Textpos.sty was already part of the original files, so need more debugging to identify the root of the deprecation (as it was working before, some package may have broken something). This package defines margins and text position, so not using it may break some things.

**Comment by themiguelamador** [comment]
@JoaoDomingos42 opted for not deleting the file, and updated it to the new version, and no longer had the error. Thanks @ana-borges for spotting the package with the error.
